# Generated by Django 2.2.6 on 2019-10-24 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('RPL', 'Rekayasa Perangkat Lunak'), ('TKJ', 'Teknik Komputer Jaringan'), ('TBSM', 'Teknik Bisnis Sepeda Motor'), ('umum', 'Umum')], max_length=100, null=True)),
                ('desc', froala_editor.fields.FroalaField()),
                ('image', models.ImageField(blank=True, upload_to='thumbnail_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
