# Generated by Django 2.2.6 on 2019-10-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_commentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
