# Generated by Django 2.2.6 on 2019-10-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191024_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, default='thumbnail_image/forum-24px.svg', upload_to='thumbnail_image/'),
        ),
    ]
